In [1]:
import torch

In [23]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3, 4, 5)
a

tensor([[[-0.4151, -1.1476,  0.3102,  0.7118, -0.5631],
         [-0.4572,  0.8055, -0.9073, -0.6255, -1.9077],
         [ 0.0976,  0.0883,  1.2831,  1.3652,  0.0394],
         [ 1.4372,  1.1992,  0.4216, -0.1508,  1.2110]],

        [[-0.4037,  0.0439, -0.8703,  0.3546, -0.0900],
         [ 0.9104, -0.5144, -0.1422, -0.0675, -0.5089],
         [ 0.0942,  0.7625, -1.1359,  2.6938,  0.3582],
         [-0.0286, -0.9990, -0.2597,  1.3374, -0.8650]],

        [[ 0.1704,  0.4125,  0.6563, -0.0988, -1.3648],
         [ 0.8540,  0.4501,  0.2109, -0.5645, -0.0519],
         [-0.3712,  0.1569, -0.4310, -0.0373, -1.6841],
         [ 0.7047, -1.8612,  0.5715,  0.5572,  0.2135]]])

In [24]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [28]:
# 3. Приведите его к форме 6х10
a = a.reshape(6, 10)

In [26]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(100, size=(10,))
b

tensor([ 4, 65, 36, 87, 79, 49, 80, 54, 99, 39])

In [29]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
c = a * b
c

tensor([[  -1.6605,  -74.5927,   11.1656,   61.9287,  -44.4823,  -22.4015,
           64.4413,  -48.9916,  -61.9254,  -74.3988],
        [   0.3906,    5.7400,   46.1911,  118.7716,    3.1095,   70.4205,
           95.9355,   22.7639,  -14.9307,   47.2274],
        [  -1.6147,    2.8528,  -31.3311,   30.8490,   -7.1075,   44.6112,
          -41.1509,   -7.6777,   -6.6854,  -19.8483],
        [   0.3768,   49.5619,  -40.8912,  234.3601,   28.2952,   -1.4027,
          -79.9239,  -14.0229,  132.3986,  -33.7331],
        [   0.6816,   26.8101,   23.6270,   -8.5986, -107.8210,   41.8439,
           36.0117,   11.3894,  -55.8825,   -2.0240],
        [  -1.4848,   10.1989,  -15.5142,   -3.2464, -133.0415,   34.5309,
         -148.8947,   30.8608,   55.1653,    8.3283]])

In [34]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
(a @ a.T).shape

torch.Size([6, 6])

In [35]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.Tensor([1]), requires_grad=True)
z = Variable(torch.Tensor([0.5]), requires_grad=True)
t = Variable(torch.Tensor([2]), requires_grad=True)

y = x ** 3 + z - 75 * t

y.backward()

print(f"Значение производной в заданной точке:\n\
        ({float(x.grad)}, {float(z.grad)}, {float(t.grad)})")

Значение производной в заданной точке:
        (3.0, 1.0, -75.0)


In [48]:
# 8. Создайте единичный тензор размера 5x6
a = torch.ones((5, 6))
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [49]:
# 9. Переведите его в формат numpy
import numpy as np

a = a.numpy()
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)